User managment
M4MController/controller-web pull request #24
Opened 2020-04-11 17:42 UTC by YAXo-O

Возможность sign_in и sign_up
Разделение страниц на закрытые и открытые
Получение списка пользователей

В конечно итоге, на винде это всё так и не запустилось, поэтому тестил на debian. Советую посмотреть не только на код, но и спулить себе и проверить, что у тебя тоже нормально запустится.

2020-04-11 17:45 UTC, YAXo-O commented on server/database/managers.py
> +            raise ObjectNotFoundError(object='Record')
UserManager - тут всё довольно очевидно

2020-04-11 17:48 UTC, YAXo-O commented on server/routing.py
Стоит поискать, как в Flask валидировать данные с клиента и отправлять ошибку на клиент, потому что вариант с пробрасыванием исключения не очевидный.

2020-04-11 17:55 UTC, ed-asriyan commented
оставлю тут)

![image](https://user-images.githubusercontent.com/7848847/79051062-b2ea5000-7c36-11ea-8e21-99ebe23f6a4d.png)

2020-04-11 18:14 UTC, ed-asriyan requested changes
не стартует

```
backend_1       | Traceback (most recent call last):
backend_1       |   File "./start.py", line 14, in <module>
backend_1       |     from server.server import app
backend_1       |   File "/application/server/server.py", line 37, in <module>
backend_1       |     app = App(config)
backend_1       |   File "/application/server/server.py", line 15, in __init__
backend_1       |     self._flask = Flask(__name__)
backend_1       |   File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 558, in __init__
backend_1       |     self.add_url_rule(
backend_1       |   File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 66, in wrapper_func
backend_1       |     return f(self, *args, **kwargs)
backend_1       |   File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1216, in add_url_rule
backend_1       |     self.url_map.add(rule)
backend_1       |   File "/usr/local/lib/python3.8/site-packages/werkzeug/routing.py", line 1562, in add
backend_1       |     rule.bind(self)
backend_1       |   File "/usr/local/lib/python3.8/site-packages/werkzeug/routing.py", line 711, in bind
backend_1       |     self.compile()
backend_1       |   File "/usr/local/lib/python3.8/site-packages/werkzeug/routing.py", line 767, in compile
backend_1       |     self._build = self._compile_builder(False)
backend_1       |   File "/usr/local/lib/python3.8/site-packages/werkzeug/routing.py", line 1128, in _compile_builder
backend_1       |     return self.BuilderCompiler(self).compile(append_unknown)
backend_1       |   File "/usr/local/lib/python3.8/site-packages/werkzeug/routing.py", line 1119, in compile
backend_1       |     co = types.CodeType(*code_args)
backend_1       | TypeError: code() takes at least 14 arguments (13 given)
```

2020-04-11 18:14 UTC, ed-asriyan commented on sensors_polling/main.py
> +				print("Failed reading data from obd!", e)
давай определимся с отступами

в этой репе юзаем табы?

2020-04-11 18:14 UTC, ed-asriyan commented on server/database/schema.sql
> +  pwd_hash VARCHAR NOT NULL
давай ещё first, last, middle name добавим. на фронте щас так
![image](https://user-images.githubusercontent.com/7848847/79051136-2e4c0180-7c37-11ea-93db-0e1c8f6fd646.png)

2020-04-11 18:14 UTC, ed-asriyan commented on server/database/schema.sql
> +  pwd_hash VARCHAR NOT NULL
и email вместо username

2020-04-11 18:14 UTC, ed-asriyan commented on server/routing.py
>              print(sensor.last_value)
принт)

2020-04-11 18:18 UTC, ed-asriyan commented on server/routing.py
> +    app.register_route(SensorDataResource, 'sensor_data_private', '/private/sensor/<int:sensor_id>/data/add')
супер!

теперь из сенсоров можно убрать postgres зависимости!

2020-04-11 18:22 UTC, ed-asriyan commented
а где проверка на дефолтные роуты, что юзер залогинен? я что-то не нашл

2020-04-19 08:03 UTC, YAXo-O commented on sensors_polling/main.py
> +				print("Failed reading data from obd!", e)
Я всегда и везде за табы)

2020-04-19 08:06 UTC, YAXo-O commented on server/database/managers.py
> +        return self.session.query(self.model).filter_by(user_id=user_id).update(info)
Пользователь разбит на две таблицы: в одной хранится инфа для авторизации (логин и хеш пароля), во второй - вся остальная инфа. Логин и хеш пароля можно только добавить новый (зарегистрировать нового пользователя), причём при создании нового пользователя создаёт объект инфы для него. Объект инфы (user_info) можно обновлять. Удаление пока не делал, если нужно будет - добавлю

2020-04-19 08:08 UTC, YAXo-O commented on server/database/models.py
> +    e_mail = Column(String)
user_info, насколько я помню, подгонялся по тот, что уже есть на беке. Если бек собираемся переделывать, имеет смысл пересмотреть, какие данные нужны, и в какие полях они хранятся? Я имею в виду типы и Nullable/Not Nullable

2020-04-19 08:09 UTC, YAXo-O commented on server/database/schema.sql
> +  pwd_hash VARCHAR NOT NULL
Чуть выше ответил касательно полей + добавил тут проверки на то, что такие таблицы уже существуют. Так же добавил создание юзера и бд, не уверен, что сработает как надо, но у меня ничего не падало как минимум)

2020-04-19 08:10 UTC, YAXo-O commented on server/errors.py
>          }
Вот тут ты забыл строчечку про статус, из-за чего декоратор с перехватыванием ошибок у нас не работал. Поправил и поставил на все запросы отловлю ошибок, чтобы можно было это уже в более-менее адекватном варианте отправлять на клиент, а не 500 ошибку в любой ситуации кидать)

2020-04-19 08:11 UTC, YAXo-O commented on server/routing.py
> +		UserInfoManager(self.db_session).save_new(user.id)
Возможно, стоит вынести в отдельную транзакцию, но я не уверен, что под капотом каждая из операций сохранения не выполняется в отдельной транзакции

2020-04-19 08:12 UTC, YAXo-O commented on server/routing.py
> +	@schematic_response(AuthSchema())
Заюзал ViewModel для входных и выходных параметров. Сначала подключил стороннюю либу, а потом увидел, что у нас под это были декораторы)

2020-04-19 08:15 UTC, YAXo-O commented on server/routing.py
> +	app.register_route(User, 'user_info_self', '/user/info')
Фласк не поддерживает опциональные url-параметры, пришлось два раза ссылаться на один и тот же endpoint и оборачивать его декоратором, который проставляет user_id из jwt, если его нет

2020-04-19 08:16 UTC, YAXo-O commented on server/validation/schema.py
> +	e_mail = fields.String()
Опять же, поля и типы user_info открыты к обсуждению и изменению, брал те, что у нас отдавались захардкоженными по аналогии с беком

2020-04-19 08:39 UTC, YAXo-O commented on server/resources/utils.py
> +
Добавил редирект на sign_in в случае, когда токен "протух"

2020-04-19 08:42 UTC, YAXo-O commented on server/database/managers.py
> +        return self.session.query(self.model).join(UserInfo.user).all()
Не знаю, что именно я делаю не так, но на клиент поле user приходит пустое.  Хотя должен бы объект с логином приходить. Опять же, не знаю, какие именно поля нужны на клиенте для списка, поэтому так же вопрос открыт к обсуждению)

2020-04-19 08:44 UTC, ed-asriyan commented on server/resources/utils.py
> +
Лучше 401 Unauthorized
На фронте проще отлавливать ошибки будет

2020-04-19 08:50 UTC, YAXo-O commented
Думаю, что мы дошли до той стадии, когда можно начать писать тесты. Что думаешь? Могу заняться этим. Потому что чекать запросы руками - дело утомительное)
Касательно твоего вопроса с проверкой jwt - он под капотом проверяет, что jwt валиден, при этом никак не связывает его с пользователем. Но из токена можно получить данные об email и id юзера, а дальше сделать запрос к базе и получить остальные данные, если это требуется. Полагаю, что в дальнейшем, если мы говорим о многопользовательской системе, нам придётся добавить в остальные таблицы так же foreign key на юзера и показывать только те данные, которые относятся к текущему юзеру.

По endpointам, на данный момент закрытые (доступны только с валидным tokenом): 

- Просмотр user_info (своей и остальных пользователей)
- Обновление user_info (только своей)
- Список объектов (любых пользователей)
- Список сенсоров (любых пользователей)
- Список всего (объектов, сенсоров, контроллеров) (любых пользователей)

Доступны любым пользователям, в том числе без tokenа и с невалидным tokenом:

- Регистрация
- Авторизация
- Список пользователей

2020-04-19 08:53 UTC, ed-asriyan commented on server/routing.py
> +		UserInfoManager(self.db_session).save_new(user.id)
в `@provide_db_session` создается новая сессия, которая создает транзакцию, так что оборачивать не надо

2020-04-19 08:57 UTC, ed-asriyan commented on server/database/models.py
> +    e_mail = Column(String)
согласен, надо подумать и обсудить. тут много лишних полей, они создавались почти 1.5 года назад)

2020-04-19 09:00 UTC, ed-asriyan commented on server/routing.py
> +	@safe_handler
им оборачиваются все запросы, так что можно не писать его в ресурсах

2020-04-19 10:19 UTC, ed-asriyan commented
понял в чем проблема запуска была. под докером не та версия питона
в Dockerfile нужно написать
```Dockerfile
FROM python:3.7
```

2020-04-19 10:22 UTC, ed-asriyan commented on server/resources/utils.py
> +
если токена нет (я просто в браузере открыл localhost:5000/objects), то 500-ка
```
backend_1     | 172.18.0.1 - - [19/Apr/2020 10:19:30] "GET /objects HTTP/1.1" 500 -
backend_1     | Missing Authorization Header
backend_1     | Traceback (most recent call last):
backend_1     |   File "/application/server/resources/utils.py", line 38, in f
backend_1     |     return func(self, *args, **kwargs)
backend_1     |   File "/usr/local/lib/python3.7/site-packages/flask_jwt_extended/view_decorators.py", line 107, in wrapper
backend_1     |     verify_jwt_in_request()
backend_1     |   File "/usr/local/lib/python3.7/site-packages/flask_jwt_extended/view_decorators.py", line 32, in verify_jwt_in_request
backend_1     |     jwt_data, jwt_header = _decode_jwt_from_request(request_type='access')
backend_1     |   File "/usr/local/lib/python3.7/site-packages/flask_jwt_extended/view_decorators.py", line 314, in _decode_jwt_from_request
backend_1     |     raise NoAuthorizationError(errors[0])
backend_1     | flask_jwt_extended.exceptions.NoAuthorizationError: Missing Authorization Header
backend_1     | 172.18.0.1 - - [19/Apr/2020 10:19:30] "GET /objects HTTP/1.1" 500 -
backend_1     | Missing Authorization Header
backend_1     | Traceback (most recent call last):
backend_1     |   File "/application/server/resources/utils.py", line 38, in f
backend_1     |     return func(self, *args, **kwargs)
backend_1     |   File "/usr/local/lib/python3.7/site-packages/flask_jwt_extended/view_decorators.py", line 107, in wrapper
backend_1     |     verify_jwt_in_request()
backend_1     |   File "/usr/local/lib/python3.7/site-packages/flask_jwt_extended/view_decorators.py", line 32, in verify_jwt_in_request
backend_1     |     jwt_data, jwt_header = _decode_jwt_from_request(request_type='access')
backend_1     |   File "/usr/local/lib/python3.7/site-packages/flask_jwt_extended/view_decorators.py", line 314, in _decode_jwt_from_request
backend_1     |     raise NoAuthorizationError(errors[0])
backend_1     | flask_jwt_extended.exceptions.NoAuthorizationError: Missing Authorization Header
backend_1     | 172.18.0.1 - - [19/Apr/2020 10:19:31] "GET /objects HTTP/1.1" 500 -
```

2020-04-19 10:24 UTC, ed-asriyan commented on server/resources/utils.py
> +
на `user/list` тоже 500

2020-04-19 10:53 UTC, ed-asriyan commented on server/database/managers.py
> +        return self.session.query(self.model).join(UserInfo.user).all()
на фронте достаточно просто факта наличия хотя бы одного юзера

2020-04-19 11:04 UTC, ed-asriyan commented
> Думаю, что мы дошли до той стадии, когда можно начать писать тесты. Что думаешь? Могу заняться этим. Потому что чекать запросы руками - дело утомительное)
> Касательно твоего вопроса с проверкой jwt - он под капотом проверяет, что jwt валиден, при этом никак не связывает его с пользователем. Но из токена можно получить данные об email и id юзера, а дальше сделать запрос к базе и получить остальные данные, если это требуется. Полагаю, что в дальнейшем, если мы говорим о многопользовательской системе, нам придётся добавить в остальные таблицы так же foreign key на юзера и показывать только те данные, которые относятся к текущему юзеру.
> 
> По endpointам, на данный момент закрытые (доступны только с валидным tokenом):
> 
>     * Просмотр user_info (своей и остальных пользователей)
> 
>     * Обновление user_info (только своей)
> 
>     * Список объектов (любых пользователей)
> 
>     * Список сенсоров (любых пользователей)
> 
>     * Список всего (объектов, сенсоров, контроллеров) (любых пользователей)
> 
> 
> Доступны любым пользователям, в том числе без tokenа и с невалидным tokenом:
> 
>     * Регистрация
> 
>     * Авторизация
> 
>     * Список пользователей

на счет тестов: пока не понятно будущее м4м, пока нет финансирования, функциональность важнее стабильности. поэтому написание тестов может быть лишней тратой сил. поэтому если ты сичтаешь, что это необходимо и съэкономит время в ближайшем будущем, я за. если нет, то завтра может оказаться, что функционал надо полностью изменить, и тесты окажутся зря написанными. если готов к такому, то пожалуйста :)

по поводу многопользовательской системы:
на контроллере пока задумывались только об однопользовательском режиме, поэтому пока нет смысла. Но! нужен клаудный бекенд, а там уже это понадобится. есть мысли не писать сервер заново, а заюзать этот код этого проекта за основу

2020-04-19 11:18 UTC, ed-asriyan commented on server/database/managers.py
> +        return self.session.query(self.model).join(UserInfo.user).all()
```python
return self.session.query(self.model).options(joinedload(UserInfo.user)).all()
```

2020-04-19 11:19 UTC, ed-asriyan commented on server/database/managers.py
> +        return self.session.query(self.model).filter_by(user_id=user_id).update(info)
пока не надо удаление

2020-04-19 11:21 UTC, ed-asriyan commented on server/validation/schema.py
> +	e_mail = fields.String()
ответил выше

2020-04-21 17:10 UTC, ed-asriyan approved these changes

2020-04-25 12:08 UTC, merged